author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: POE-Component-WWW-Shorten
no_index: 
  directory: 
    - inc
    - t
requires: 
  Carp: 0
  POE: 0.38
  WWW::Shorten: 1.95
version: 1.06
