# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         POE-Component-WWW-Shorten
version:      1.02
version_from: lib/POE/Component/WWW/Shorten.pm
installdirs:  site
requires:
    Carp:                          0
    POE:                           0.31
    WWW::Shorten:                  1.95

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
