author: 'Chris Williams <chris@bingosnet.co.uk>'
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
module_name: POE::Component::WWW::Shorten
name: POE-Component-WWW-Shorten
no_index:
  directory:
    - inc
    - t
requires:
  Carp: 0
  POE: 0.31
  WWW::Shorten: 1.95
version: 1.03
